name: Test ntptfs-rs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install WinFSP
      run: choco install winfsp
    - name: Build winfsp-rs
      run: cargo build --verbose
