name: Test ntptfs-rs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 6"
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nightly Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
    - name: Install WinFSP
      run: choco install winfsp
    - name: Build ntptfs
      run: cargo build -p ntptfs-winfsp-rs --verbose
    - name: Test ntptfs
      shell: cmd
      run: |
        mkdir D:\a\test
        start /b "" cargo run --bin ntptfs-winfsp-rs -- -p D:\a\test -m R:
        echo "Waiting 45 seconds for ntptfs to start"
        waitfor /T 45 pause 2>NUL
        R:
        ${{ github.workspace }}\test\winfsp-test\winfsp-tests-x64 --external --resilient +* --case-insensitive-cmp -delete_access_test -getfileattr_test -exec_rename_dir_test -rename_flipflop_test -stream_rename_flipflop_test -stream_getstreaminfo_test -ea*
